/**
 * IMPORTANT! This file is auto-generated.
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is created by a script when running 'npm run dev' or 'npm run build'.
 * It combines various schema definitions into a single exportable module.
 *
 * Any manual changes made to this file will be overwritten the next time the
 * generation script runs. If you need to modify the schemas, please edit
 * the individual schema files. The script 'scripts/schema.ts' reads all schema
 * files in the 'src/db/schema' directory and combines them into this module.
 *
 * This automated process ensures that our schema definitions are centralized
 * and consistently structured for use throughout the application.
 * use `npm run schema:generate` to regenerate this file
 */

import AuthenticationSchema from './Authentication.schema';
import AuthXTokenSchema from './AuthXToken.schema';
import BusinessProfileSchema from './BusinessProfile.schema';
import BusinessRoleFunctionsSchema from './BusinessRoleFunctions.schema';
import BusinessRolesSchema from './BusinessRoles.schema';

const schemas = [
  AuthenticationSchema,
  AuthXTokenSchema,
  BusinessProfileSchema,
  BusinessRoleFunctionsSchema,
  BusinessRolesSchema,
];
const combinedSchema = schemas.reduce((acc, schema) => {
  const sym = Symbol.for('drizzle:BaseName');
  const name = schema[sym];

  return {
    ...acc,
    [name]: schema,
  };
}, {});

export default combinedSchema;
