import fs from 'fs';
import path from 'path';

const schemaDirectoryPath = path.join(__dirname, '../src/db/schema');
const outputFile = path.join(schemaDirectoryPath, 'index.ts');

const files = fs.readdirSync(schemaDirectoryPath);

const imports: string[] = [];
const combinedSchema: string[] = [];

files.forEach((file) => {
  if (file.endsWith('.schema.ts') && file !== 'index.ts') {
    const baseName = file.replace('.schema.ts', '');
    const schemaName = `${baseName}Schema`;

    imports.push(`import ${schemaName} from './${baseName}.schema';`);
    combinedSchema.push(`${baseName}: ${schemaName}`);
  }
});

const outputContent = `/**
 * IMPORTANT! This file is auto-generated.
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is created by a script when running 'npm run dev' or 'npm run build'.
 * It combines various schema definitions into a single exportable module.
 *
 * Any manual changes made to this file will be overwritten the next time the
 * generation script runs. If you need to modify the schemas, please edit
 * the individual schema files. The script 'scripts/schema.ts' reads all schema
 * files in the 'src/db/schema' directory and combines them into this module.
 *
 * This automated process ensures that our schema definitions are centralized
 * and consistently structured for use throughout the application.
 * use \`npm run schema:generate\` to regenerate this file
 */

${imports.join('\n')}

const sym = Symbol.for('drizzle:BaseName');
const combinedSchema = {
  ${combinedSchema.join(',\n  ')},
};

Object.keys(combinedSchema).forEach((key: string) => {
  const schema = combinedSchema[key];
  const name = schema[sym];

  if (key !== name) {
    throw new Error(\`Schema name mismatch: "\${key}" !== "\${name}" table name.\`);
  }
});

export default combinedSchema;
`;

console.log('Generating schema index file...');
fs.writeFileSync(outputFile, outputContent);
